CREATE TABLE IF NOT EXISTS HEADER_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    organization          VARCHAR,
    organization_license  VARCHAR,
    organization_contacts VARCHAR,
    branch                VARCHAR,
    branch_contacts       VARCHAR,
    license_branch        VARCHAR,
    department            VARCHAR,
    department_contacts   VARCHAR,
    department_license    VARCHAR,
    CONSTRAINT pk_headerTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_HEADER_TEMPLATES UNIQUE (reporting_document_id)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLE_TEMPLATES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporting_document_id        BIGINT                                  NOT NULL,
    header_id                    BIGINT                                  NOT NULL,
    document_name                VARCHAR                                 NOT NULL,
    document_title               VARCHAR                                 NOT NULL,
    object_string                VARCHAR,
    installation_location_string VARCHAR,
    address_string               VARCHAR,
    signature_string             VARCHAR,
    city                         VARCHAR,
    year                         VARCHAR,
    CONSTRAINT pk_pageTitleTemplate PRIMARY KEY (id),
    CONSTRAINT FK_PAGE_TITLE_TEMPLATES_ON_HEADER_TEMPLATES FOREIGN KEY (header_id) REFERENCES header_templates (id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id        BIGINT                                  NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    document_type         VARCHAR                                 NOT NULL,
    document_name         VARCHAR                                 NOT NULL,
    document_title        VARCHAR                                 NOT NULL,
    header_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_protocolTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_PROTOCOL_TEMPLATES UNIQUE (object_type_id, document_type, document_name),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_HEADER_TEMPLATES FOREIGN KEY (header_id) REFERENCES header_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id        BIGINT                                  NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    page_title_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_REPORT_TEMPLATES UNIQUE (object_type_id, reporting_document_id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_PAGE_TITLE_TEMPLATES FOREIGN KEY (page_title_id) REFERENCES page_title_templates (id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    sequential_number     INTEGER                                 NOT NULL,
    section_name          VARCHAR                                 NOT NULL,
    CONSTRAINT pk_sectionTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_SECTION_TEMPLATES UNIQUE (reporting_document_id, sequential_number, section_name)
);

CREATE TABLE IF NOT EXISTS REPORT_SECTION_TEMPLATES
(
    report_id  BIGINT,
    section_id BIGINT,
    CONSTRAINT pk_report_templates_of_sections_templates PRIMARY KEY (report_id, section_id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_DATA_TEMPLATES
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subsection_data_type VARCHAR                                 NOT NULL,
    subsection_data      VARCHAR                                 NOT NULL,
    CONSTRAINT pk_subsectionDataTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    section_id              BIGINT                                  NOT NULL,
    subsection_data_type    VARCHAR                                 NOT NULL,
    sequential_number       DOUBLE PRECISION                        NOT NULL,
    subsection_name         VARCHAR                                 NOT NULL,
    subsection_text         VARCHAR,
    conclusions_template_id BIGINT,
    CONSTRAINT pk_subsectionTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_SUBSECTION_DATA_TEMPLATES UNIQUE (section_id, subsection_data_type)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_SUBSECTION_DATA_TEMPLATES
(
    subsection_id      BIGINT,
    subsection_data_id BIGINT,
    CONSTRAINT pk_subsection_templates_of_subsection_data_templates PRIMARY KEY (subsection_id, subsection_data_id)
);

CREATE TABLE IF NOT EXISTS SECTION_SUBSECTION_TEMPLATES
(
    section_id    BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_section_templates_of_subsection_templates PRIMARY KEY (section_id, subsection_id)
);
