CREATE TABLE IF NOT EXISTS HEADER_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    organization          VARCHAR,
    organization_license  VARCHAR,
    organization_contacts VARCHAR,
    branch                VARCHAR,
    branch_contacts       VARCHAR,
    license_branch        VARCHAR,
    department            VARCHAR,
    department_contacts   VARCHAR,
    department_license    VARCHAR,
    CONSTRAINT pk_headerTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_HEADER_TEMPLATES UNIQUE (reporting_document_id)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLE_TEMPLATES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id               BIGINT                                  NOT NULL,
    reporting_document_id        BIGINT                                  NOT NULL,
    header_id                    BIGINT                                  NOT NULL,
    document_name                VARCHAR                                 NOT NULL,
    document_title               VARCHAR                                 NOT NULL,
    object_string                VARCHAR,
    installation_location_string VARCHAR,
    address_string               VARCHAR,
    signature_string             VARCHAR,
    city                         VARCHAR,
    year                         VARCHAR,
    CONSTRAINT pk_pageTitleTemplate PRIMARY KEY (id),
    CONSTRAINT FK_PAGE_TITLE_TEMPLATES_ON_HEADER_TEMPLATES FOREIGN KEY (header_id) REFERENCES header_templates (id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id        BIGINT                                  NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    protocol_type         VARCHAR                                 NOT NULL,
    document_name         VARCHAR                                 NOT NULL,
    document_title        VARCHAR                                 NOT NULL,
    header_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_protocolTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_PROTOCOL_TEMPLATES UNIQUE (object_type_id, protocol_type, document_name),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_HEADER_TEMPLATES FOREIGN KEY (header_id) REFERENCES header_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id        BIGINT                                  NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    page_title_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_REPORT_TEMPLATES UNIQUE (object_type_id, reporting_document_id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_PAGE_TITLE_TEMPLATES FOREIGN KEY (page_title_id) REFERENCES page_title_templates (id)
);

CREATE TABLE IF NOT EXISTS TABLE_TEMPLATES
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    protocol_type        VARCHAR,
    subsection_data_type VARCHAR,
    table_data_type      VARCHAR,
    sequential_number    INTEGER,
    table_name           VARCHAR,
    CONSTRAINT pk_tableTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TABLES_TEMPLATES
(
    protocol_id BIGINT,
    table_id    BIGINT,
    CONSTRAINT pk_protocol_templates_of_table_templates PRIMARY KEY (protocol_id, table_id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id        BIGINT                                  NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    sequential_number     INTEGER                                 NOT NULL,
    section_name          VARCHAR                                 NOT NULL,
    CONSTRAINT pk_sectionTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_SECTION_TEMPLATES UNIQUE (object_type_id, reporting_document_id, section_name)
);

CREATE TABLE IF NOT EXISTS REPORT_SECTION_TEMPLATES
(
    report_id  BIGINT,
    section_id BIGINT,
    CONSTRAINT pk_report_templates_of_sections_templates PRIMARY KEY (report_id, section_id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_DATA_TEMPLATES
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subsection_data_type VARCHAR                                 NOT NULL,
    division_id          BIGINT,
    object_type_id       BIGINT,
    subsection_data      VARCHAR                                 NOT NULL,
    CONSTRAINT pk_subsectionDataTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_SUBSECTION_TEMPLATES
(
    protocol_id   BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_protocol_templates_of_subsections_templates PRIMARY KEY (protocol_id, subsection_id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subsection_data_type    VARCHAR                                 NOT NULL,
    sequential_number       DOUBLE PRECISION                        NOT NULL,
    subsection_name         VARCHAR                                 NOT NULL,
    subsection_text         VARCHAR,
    table_id                BIGINT,
    conclusions_template_id BIGINT,
    CONSTRAINT pk_subsectionTemplate PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_TABLE_TEMPLATES FOREIGN KEY (table_id) REFERENCES table_templates (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_SUBSECTION_DATA_TEMPLATES
(
    subsection_id      BIGINT,
    subsection_data_id BIGINT,
    CONSTRAINT pk_subsection_templates_of_subsection_data_templates PRIMARY KEY (subsection_id, subsection_data_id)
);

CREATE TABLE IF NOT EXISTS SECTION_SUBSECTION_TEMPLATES
(
    section_id    BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_section_templates_of_subsection_templates PRIMARY KEY (section_id, subsection_id)
);

CREATE TABLE IF NOT EXISTS PASSPORT_DATA_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number VARCHAR                                 NOT NULL,
    data_name         VARCHAR                                 NOT NULL,
    apply_report      BOOLEAN                                 NOT NULL,
    apply_protocol    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_passportDataTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_PASSPORT_DATA_TEMPLATES UNIQUE (sequential_number, data_name)
);

CREATE TABLE IF NOT EXISTS SECTION_PASSPORT_DATA_TEMPLATES
(
    section_id       BIGINT,
    passport_data_id BIGINT,
    CONSTRAINT pk_passport_data_templates_of_section_templates PRIMARY KEY (section_id, passport_data_id)
);

CREATE TABLE IF NOT EXISTS COLUMNS_HEADERS_TEMPLATES
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    column_data_type       VARCHAR                                 NOT NULL,
    sequential_cell_number INTEGER                                 NOT NULL,
    cell_name              VARCHAR                                 NOT NULL,
    CONSTRAINT pk_columnHeader PRIMARY KEY (id),
    CONSTRAINT UQ_COLUMNS_HEADERS_TEMPLATES UNIQUE (sequential_cell_number, cell_name)
);

CREATE TABLE IF NOT EXISTS TABLE_COLUMNS_HEADERS_TEMPLATES
(
    table_id          BIGINT,
    columns_header_id BIGINT,
    CONSTRAINT pk_table_templates_of_columns_headers_template PRIMARY KEY (table_id, columns_header_id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_TEMPLATES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id          BIGINT                                  NOT NULL,
    reporting_document_id   BIGINT                                  NOT NULL,
    protocol_type           VARCHAR                                 NOT NULL,
    protocol_name           VARCHAR                                 NOT NULL,
    sequential_number       INTEGER                                 NOT NULL,
    protocol_title          VARCHAR                                 NOT NULL,
    text                    VARCHAR,
    conclusions_template_id BIGINT,
    CONSTRAINT pk_reportProtocolTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_SUBSECTION_TEMPLATES
(
    protocol_id    BIGINT,
    subsections_id BIGINT,
    CONSTRAINT pk_report_protocol_templates_of_subsections_templates PRIMARY KEY (protocol_id, subsections_id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_TABLE_TEMPLATES
(
    protocol_id BIGINT,
    table_id    BIGINT,
    CONSTRAINT pk_report_protocol_templates_of_table_header_templates PRIMARY KEY (protocol_id, table_id)
);